version: 2.1
orbs:
  # https://github.com/cypress-io/circleci-orb
  cypress: cypress-io/cypress@1

workflows:
  build:
    jobs:
      - cypress/run:
          filters:
            branches:
              ignore:
                - gh-pages
          post-checkout:
            - run: echo "Checking out the application"
            - run: git clone git@github.com:bahmutov/next-ts-app.git --depth 1
          config: 'baseUrl=https://next-ts-app-swart.vercel.app/'
          no-workspace: true
          post-steps:
            - store_artifacts:
                path: coverage/lcov-report
