version: 2.1
orbs:
  # https://github.com/cypress-io/circleci-orb
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/run:
          filters:
            branches:
              ignore:
                - gh-pages
          config: 'baseUrl=https://next-ts-app-swart.vercel.app/'
          no-workspace: true
          post-steps:
            - store_artifacts:
                path: coverage/lcov-report
