name: ci
on: push
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v2

      - name: Run tests against the production site 🧪
        # https://github.com/cypress-io/github-action
        uses: cypress-io/github-action@v2
        with:
          config: 'baseUrl=https://next-ts-app-swart.vercel.app/'
        env:
          DEBUG: code-coverage

      # TODO: publish the code coverage HTML report to GitHub Pages
